import re

with open('resources.html', 'r', encoding='utf-8-sig') as f:
    content = f.read()

new_tab = r"""                <div id="tab-papers" class="tab-content">
                    <p style="margin-bottom: 20px; color: var(--text-secondary); font-size: 0.9rem;">15 seminal academic papers in Operations Management and Supply Chain, curated from FT-50 and INFORMS journals.</p>
                    <div class="grid-3" style="gap: 16px;">
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Bullwhip Effect (1997)</h3><p style="font-size:0.79rem;">Lee, Padmanabhan &amp; Whang - Quantifying demand amplification. <em>Management Science</em>.</p><a href="https://pubsonline.informs.org/doi/10.1287/mnsc.43.4.546" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Supply Chain Resilience (2005)</h3><p style="font-size:0.79rem;">Sheffi &amp; Rice - A supply chain view of the resilient enterprise. <em>MIT Sloan Management Review</em>.</p><a href="https://sloanreview.mit.edu/article/a-supply-chain-view-of-the-resilient-enterprise/" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Toyota Production System (1977)</h3><p style="font-size:0.79rem;">Sugimori et al. - Original paper on TPS and Just-In-Time. <em>Int'l Journal of Production Research</em>.</p><a href="https://www.tandfonline.com/doi/abs/10.1080/00207547708943149" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">Newsvendor Contracting (2001)</h3><p style="font-size:0.79rem;">Cachon &amp; Lariviere - Contracting to assure supply. <em>Management Science, INFORMS</em>.</p><a href="https://pubsonline.informs.org/doi/10.1287/mnsc.47.7.943.9806" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">Lean Thinking (1996)</h3><p style="font-size:0.79rem;">Womack &amp; Jones - Banish Waste and Create Wealth in your Corporation. <em>Journal of OM</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/S0272696397818027" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Theory of Constraints (1990)</h3><p style="font-size:0.79rem;">Goldratt - What is this thing called Theory of Constraints? <em>North River Press</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/0925527394900124" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">EOQ Classic (1913/1990)</h3><p style="font-size:0.79rem;">Harris (1913) - How Many Parts to Make at Once. Reprinted in <em>Operations Research</em>, INFORMS.</p><a href="https://pubsonline.informs.org/doi/10.1287/opre.38.6.947" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Six Sigma Implementation (2002)</h3><p style="font-size:0.79rem;">Antony &amp; Banuelas - Key ingredients for effective Six Sigma. <em>Measuring Business Excellence</em>.</p><a href="https://www.emerald.com/insight/content/doi/10.1108/13683040210451679/full/html" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Inventory Pooling (1979)</h3><p style="font-size:0.79rem;">Eppen - Effects of centralization on multi-location newsboy problem. <em>Management Science</em>.</p><a href="https://pubsonline.informs.org/doi/10.1287/mnsc.25.5.498" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">Sustainable Supply Chains (2008)</h3><p style="font-size:0.79rem;">Seuring &amp; Muller - Literature review to conceptual framework. <em>Journal of Cleaner Production</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/S0959652608000614" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">Digital Supply Chains (2018)</h3><p style="font-size:0.79rem;">Buyukozkan &amp; Gocer - Digital SC framework. <em>Computers in Industry</em>, Elsevier.</p><a href="https://www.sciencedirect.com/science/article/pii/S0166361517305031" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Revenue Management (2004)</h3><p style="font-size:0.79rem;">Talluri &amp; van Ryzin - Theory and Practice of Revenue Management. <em>Springer</em>.</p><a href="https://link.springer.com/book/9781402077012" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Demand Forecasting M4 (2020)</h3><p style="font-size:0.79rem;">Makridakis et al. - M4 Competition results and findings. <em>International Journal of Forecasting</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/S0169207019301128" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Vendor-Managed Inventory (1999)</h3><p style="font-size:0.79rem;">Waller et al. - VMI in the retail supply chain. <em>Journal of Business Logistics</em>.</p><a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/j.2158-1592.1999.tb00252.x" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">MRP-II Evolution (1984)</h3><p style="font-size:0.79rem;">Wight - Manufacturing Resource Planning: MRPII. <em>Int'l Journal of Production Research</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/0272696386900044" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                    </div>
                </div>"""

pattern = re.compile(
    r'                <div id="tab-papers" class="tab-content">.*?                </div>(?=\r?\n\r?\n                <div id="tab-cases")',
    re.DOTALL
)

result, count = re.subn(pattern, new_tab, content)
print(f"Substitutions: {count}")
with open('resources.html', 'w', encoding='utf-8') as f:
    f.write(result)
print("Done")
