import re

with open('resources.html', 'r', encoding='utf-8-sig') as f:
    content = f.read()

# ── NEW PAPERS TAB ──────────────────────────────────────────────
new_papers = r"""                <div id="tab-papers" class="tab-content">
                    <p style="margin-bottom:20px;color:var(--text-secondary);font-size:0.9rem;">Curated research papers featuring works by <strong>Prof. M.S. Narassima</strong> and <strong>Dr. M. Thenarasu</strong> on supply chain, job shop scheduling, and simulation, alongside classic OM references.</p>
                    <h3 style="margin-bottom:14px;font-size:1rem;color:var(--accent-blue);">Featured Works — Narassima & Thenarasu</h3>
                    <div class="grid-3" style="gap:16px;margin-bottom:24px;">
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Multi-Criteria Flexible Job Shop Scheduling (2024)</h3><p style="font-size:0.79rem;">Thenarasu, M., Rameshkumar, K., Di Mascolo, M., Anbuudayasankar, S.P. — Integrating simulation modelling with MCDM to optimize complex FJSP. <em>Int'l Journal of Production Research</em>.</p><a href="https://www.tandfonline.com/journals/tprs20" target="_blank" style="font-size:0.79rem;">View Journal</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Priority Decision Rules Using MCDM (2022)</h3><p style="font-size:0.79rem;">Thenarasu, M., Rameshkumar, K., Rousseau, J., Anbuudayasankar, S.P. — Hybrid dispatching rules for dynamic flexible job shop scheduling. <em>Simulation Modelling Practice and Theory</em>.</p><a href="https://www.sciencedirect.com/journal/simulation-modelling-practice-and-theory" target="_blank" style="font-size:0.79rem;">View Journal</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Priority Dispatching & Scheduling Algorithm (2022)</h3><p style="font-size:0.79rem;">Narassima, M.S., Vasudevan, S.K., Anbuudayasankar, S.P. — Novel algorithm for minimizing makespan, setup time, and transportation time in job shops. <em>Int'l Journal of Computer Aided Engineering &amp; Technology</em>.</p><a href="https://www.inderscience.com/jhome.php?jcode=ijcaet" target="_blank" style="font-size:0.79rem;">View Journal</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">MCDM for Press-Shop Makespan Optimization (2019)</h3><p style="font-size:0.79rem;">Thenarasu, M., Rameshkumar, K., Anbuudayasankar, S.P. — Applying MCDM (AHP, TOPSIS) in a large-scale industrial press-shop. <em>Int'l Journal of Industrial Engineering</em>.</p><a href="https://journals.sfu.ca/ijietap/index.php/ijie" target="_blank" style="font-size:0.79rem;">View Journal</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">Inventory Policy in Closed-Loop Supply Chain (2025)</h3><p style="font-size:0.79rem;">Thenarasu, M., Pai, V., Narassima, M.S., et al. — Discrete event simulation for CLSC inventory analysis. <em>Int'l Journal of Management Science &amp; Engineering Management</em>.</p><a href="https://www.tandfonline.com/journals/tmse20" target="_blank" style="font-size:0.79rem;">View Journal</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Supply Chain Resilience Index (Fuzzy Logic)</h3><p style="font-size:0.79rem;">Narassima, M.S. et al. — Measuring supply chain resilience via coexistent resilience index using fuzzy logic and simulation. Published in operations research context.</p><a href="https://scholar.google.com/citations?hl=en&user=RDFCAzYAAAAJ" target="_blank" style="font-size:0.79rem;">Google Scholar</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">COVID-19 Vaccine Distribution (Agent-Based Model)</h3><p style="font-size:0.79rem;">Narassima, M.S. et al. — Agent-based model and Grey Relational Analysis for rational vaccine distribution policy. Published in public health operations research.</p><a href="https://www.researchgate.net/profile/Narassima-M-S" target="_blank" style="font-size:0.79rem;">ResearchGate</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Repurposing Manufacturing During COVID-19</h3><p style="font-size:0.79rem;">Narassima, M.S. et al. — Simulation of manufacturing capacity repurposing during pandemic disruption. <em>arXiv (Operations Research)</em>.</p><a href="https://arxiv.org/search/?query=narassima+manufacturing&searchtype=all" target="_blank" style="font-size:0.79rem;">arXiv</a></div>
                    </div>
                    <h3 style="margin-bottom:14px;font-size:1rem;color:var(--accent-purple);">Classic OM Reference Papers</h3>
                    <div class="grid-3" style="gap:16px;">
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Bullwhip Effect (1997)</h3><p style="font-size:0.79rem;">Lee, Padmanabhan &amp; Whang — Quantifying demand amplification in supply chains. <em>Management Science</em>.</p><a href="https://pubsonline.informs.org/doi/10.1287/mnsc.43.4.546" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Toyota Production System (1977)</h3><p style="font-size:0.79rem;">Sugimori et al. — Original academic paper on TPS and Just-In-Time. <em>Int'l Journal of Production Research</em>.</p><a href="https://www.tandfonline.com/doi/abs/10.1080/00207547708943149" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">Theory of Constraints (1990)</h3><p style="font-size:0.79rem;">Goldratt — What is this thing called Theory of Constraints? <em>North River Press</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/0925527394900124" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">Lean Thinking (1996)</h3><p style="font-size:0.79rem;">Womack &amp; Jones — Banish Waste and Create Wealth in your Corporation. <em>Journal of Operations Management</em>.</p><a href="https://www.sciencedirect.com/science/article/pii/S0272696397818027" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Supply Chain Resilience (2005)</h3><p style="font-size:0.79rem;">Sheffi &amp; Rice — A supply chain view of the resilient enterprise. <em>MIT Sloan Management Review</em>.</p><a href="https://sloanreview.mit.edu/article/a-supply-chain-view-of-the-resilient-enterprise/" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">EOQ Classic (1913/1990)</h3><p style="font-size:0.79rem;">Harris (1913) — How Many Parts to Make at Once. Reprinted in <em>Operations Research</em>, INFORMS.</p><a href="https://pubsonline.informs.org/doi/10.1287/opre.38.6.947" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Digital Supply Chains (2018)</h3><p style="font-size:0.79rem;">Buyukozkan &amp; Gocer — Digital SC framework. <em>Computers in Industry</em>, Elsevier.</p><a href="https://www.sciencedirect.com/science/article/pii/S0166361517305031" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                    </div>
                </div>"""

# ── NEW CASE STUDIES TAB ─────────────────────────────────────────
new_cases = r"""                <div id="tab-cases" class="tab-content">
                    <p style="margin-bottom:20px;color:var(--text-secondary);font-size:0.9rem;">Real-world company case studies from news reports, industry white papers, and analyst publications — covering operations failures, resilience strategies, and digital transformations.</p>
                    <div class="grid-3" style="gap:16px;">
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Toyota: Just-In-Time vs. Resilience</h3><p style="font-size:0.79rem;">Post-2011 Fukushima earthquake, Toyota rebuilt its supply chain with dual sourcing and safety stock buffers while retaining lean principles. A landmark case in resilience design.</p><a href="https://www.supplychainbrain.com/articles/32046-what-toyota-learned-from-disaster" target="_blank" style="font-size:0.79rem;">Read Case</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">Apple: iPhone Supply Chain Disruption (2022)</h3><p style="font-size:0.79rem;">COVID lockdowns at Foxconn's Zhengzhou plant caused a 6M unit iPhone shortfall. Apple responded by accelerating supplier diversification to India and Vietnam.</p><a href="https://www.wsj.com/articles/apple-china-iphone-foxconn-11672060009" target="_blank" style="font-size:0.79rem;">Read WSJ Report</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Amazon: Fulfillment Network Optimization</h3><p style="font-size:0.79rem;">Amazon's "Supply Chain by Amazon" initiative uses AI and robotics to enable same-day delivery and fractional inventory management across 1,000+ fulfilment centers globally.</p><a href="https://www.aboutamazon.com/news/operations" target="_blank" style="font-size:0.79rem;">Read Amazon</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">Walmart: AI-Driven Inventory Forecasting</h3><p style="font-size:0.79rem;">Walmart deployed AI forecasting across markets in US, Mexico, Canada, and Costa Rica, rerouting shipments proactively and reducing out-of-stock events by 30%.</p><a href="https://corporate.walmart.com/news/2024/01/31/walmart-is-using-generative-ai-to-enhance-the-shopping-experience" target="_blank" style="font-size:0.79rem;">Read Case</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Boeing 787: BOM & Production Complexity</h3><p style="font-size:0.79rem;">Boeing's distributed manufacturing of the 787 Dreamliner across 50 global suppliers created unprecedented BOM and coordination challenges, leading to 3-year delays and billions in cost overruns.</p><a href="https://hbr.org/2011/09/the-world-is-flat-revisited" target="_blank" style="font-size:0.79rem;">Read HBR</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Red Sea Crisis: Global Rerouting (2024)</h3><p style="font-size:0.79rem;">Houthi attacks on Red Sea shipping in late 2023 forced global carriers to reroute around the Cape of Good Hope, adding 10-14 days of transit and disrupting MPS timelines worldwide.</p><a href="https://www.supplychaindive.com/news/red-sea-shipping-disruption-supply-chain-impact/703893/" target="_blank" style="font-size:0.79rem;">Read Article</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Zara (Inditex): Fast Fashion Supply Chain</h3><p style="font-size:0.79rem;">Zara's vertically integrated supply chain enables new designs to reach stores in 2 weeks. A classic Stevenson textbook case on responsive capacity and agile MPS.</p><a href="https://www.mckinsey.com/industries/retail/our-insights/fashion-on-demand" target="_blank" style="font-size:0.79rem;">Read McKinsey</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">COVID-19: Semiconductor Chip Shortage</h3><p style="font-size:0.79rem;">A 2-3 year global chip shortage (2020-2023) disrupted automotive and electronics manufacturers, illustrating the danger of single-source supply and the need for MRP safety stock.</p><a href="https://www2.deloitte.com/us/en/insights/industry/technology/technology-media-and-telecom-predictions/2022/semiconductor-shortage-impact.html" target="_blank" style="font-size:0.79rem;">Deloitte Report</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">Maersk: Digital Supply Chain Twin</h3><p style="font-size:0.79rem;">Maersk built a digital twin of its ocean freight network, enabling real-time capacity planning and re-routing. Featured in Gartner Top 25 Supply Chains, 2023.</p><a href="https://www.maersk.com/news/articles/2023/04/04/the-future-of-logistics-is-digital" target="_blank" style="font-size:0.79rem;">Read Maersk</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #d97706;"><h3 style="font-size:0.88rem;">IKEA: Flat-Pack BOM & Global Sourcing</h3><p style="font-size:0.79rem;">IKEA's iconic product design is driven by reverse BOM costing — designers must achieve target cost before finalizing the BOM. A case study in cost rollup and design for supply chain.</p><a href="https://hbr.org/2018/11/how-ikea-manages-its-global-workforce" target="_blank" style="font-size:0.79rem;">Read HBR</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #7c3aed;"><h3 style="font-size:0.88rem;">Tesla: Vertical Integration & Capacity Planning</h3><p style="font-size:0.79rem;">Tesla's Gigafactory model is a real-world capacity planning exercise at scale — planning for 500 GWh/year battery production using shift-based effective capacity calculations.</p><a href="https://www.mckinsey.com/industries/automotive-and-assembly/our-insights/the-future-of-the-electric-vehicle-market" target="_blank" style="font-size:0.79rem;">McKinsey Report</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #0891b2;"><h3 style="font-size:0.88rem;">Panama Canal Drought: Capacity Constraints (2023)</h3><p style="font-size:0.79rem;">A severe drought in 2023 reduced Canal transit slots by 40%, forcing shippers to cap vessel sizes. A live example of capacity constraint impacting APP and MPS globally.</p><a href="https://www.supplychaindive.com/news/panama-canal-drought-shipping-congestion-impact/698987/" target="_blank" style="font-size:0.79rem;">Read Article</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #2563eb;"><h3 style="font-size:0.88rem;">Nike: Demand Forecasting Failure (2022)</h3><p style="font-size:0.79rem;">Nike over-ordered inventory post-COVID, resulting in a massive excess stock write-down. A textbook case of APP mismatch between forecast and realized demand.</p><a href="https://www.wsj.com/articles/nike-stock-falls-as-inventories-balloon-orders-slow-11664322534" target="_blank" style="font-size:0.79rem;">WSJ Report</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #dc2626;"><h3 style="font-size:0.88rem;">Harley-Davidson: MRP Implementation</h3><p style="font-size:0.79rem;">Harley-Davidson's successful MRP-II implementation in the 1980s is a classic textbook case study featured in Stevenson Ch.14 — reducing inventory by 75% and lead times dramatically.</p><a href="https://www.sciencedirect.com/science/article/pii/026382239190150H" target="_blank" style="font-size:0.79rem;">Read Paper</a></div>
                        <div class="resource-card" style="padding:16px;border-left:4px solid #059669;"><h3 style="font-size:0.88rem;">3M: Aggregate Planning Flexibility</h3><p style="font-size:0.79rem;">3M shifted from pure level strategy to mixed APP during COVID-19 to produce N95 masks at 1.1 billion/year — a live case in rapid capacity switching and workforce planning.</p><a href="https://www.3m.com/3M/en_US/resiliency/" target="_blank" style="font-size:0.79rem;">3M Report</a></div>
                    </div>
                </div>"""

# Replace tab-papers
pattern_papers = re.compile(
    r'                <div id="tab-papers" class="tab-content">.*?                </div>(?=\r?\n\r?\n                <div id="tab-cases")',
    re.DOTALL
)
content, n1 = re.subn(pattern_papers, new_papers, content)
print(f"Papers replacements: {n1}")

# Replace tab-cases
pattern_cases = re.compile(
    r'                <div id="tab-cases" class="tab-content">.*?                </div>(?=\r?\n\r?\n                <div id="tab-reports")',
    re.DOTALL
)
content, n2 = re.subn(pattern_cases, new_cases, content)
print(f"Cases replacements: {n2}")

with open('resources.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("Done")
